### ISSUE TITLE
Recurse Demo

### ISSUE THREAD

**Issue by zephraph** [zephraph/deno-faas#8]
## Work to do

- [x] Setup demo page
- [x] Build out demo web view that shows each user's http worker in an iframe
- [x] Write demo script to connect to the client
- [ ] Setup backup script to populate workers that we build
- [ ] Rework supervisor to be runnable remotely

**Comment by sbmsr** [comment]
- [x] on resubmit, replace old iframe
- [x] on enter, submit prompt
- [x] module system
- [x] spin down functions after no request received for n minutes
